const PLATFORMS = {
  PRIME_VIDEO: 'PRIME_VIDEO',
  NETFLIX: 'NETFLIX',
  DISNEY_PLUS: 'DISNEY_PLUS',
  STAR_PLUS: 'STAR_PLUS',
  HBO_MAX: 'HBO_MAX',
  PARAMOUNT_PLUS: 'PARAMOUNT_PLUS',
  COMBO_PLUS: 'COMBO_PLUS',
};

export default PLATFORMS;
